# This Alias must point to the directory where the git repo is installed
Alias "/fancy-directory-index/" "/data/www/fancy-directory-index/"
#
#   Icon theme: apt install breeze-icon-theme
#
#Alias "/fdi-icon-theme/" "/usr/share/icons/breeze/"
#
#   Install
#   cp example.conf /etc/apache2/sites-available/fancy-directory-index.conf
#   a2ensite fancy-directory-index.conf
#
<Directory />
    AllowOverride None
    allow from all
    #Enable Dirlist & ENable Sym Links
    Options Indexes MultiViews FollowSymLinks
    # Dirlist
    IndexOptions +FoldersFirst
    IndexOptions +SuppressHTMLPreamble
    IndexOptions +IconsAreLinks
    IndexOptions +SuppressDescription
    # Load Custon Site
    AddType text/html .shtml
    HeaderName /fancy-directory-index/HEADER.shtml
    ReadmeName /fancy-directory-index/README.shtml
    
    #Custom Icons
    AddIconByType (IMG,/fancy-directory-index/assets/mimetypes/image-x-generic.png) image/*
    AddIconByType (TXT,/fancy-directory-index/assets/mimetypes/text-x-generic.png) text/*
    AddIconByType (AUD,/fancy-directory-index/assets/mimetypes/audio-x-generic.png) audio/*
    AddIconByType (PDF,/fancy-directory-index/assets/mimetypes/application-pdf.png) application/pdf
    AddIconByType (VID,/fancy-directory-index/assets/mimetypes/video-x-generic.png) video/*
    AddIconByType ("",/fancy-directory-index/assets/mimetypes/application-x-font-ttf.png) font/*
    # archives
    AddIcon /fancy-directory-index/assets/mimetypes/application-x-archive.png .tar.gz .tar.xz .tar
    AddIcon /fancy-directory-index/assets/mimetypes/application-x-archive.png .zip .7z
    # C/C++
    AddIcon /fancy-directory-index/assets/mimetypes/text-x-chdr.png .h
    AddIcon /fancy-directory-index/assets/mimetypes/text-x-csrc.png .c
    AddIcon /fancy-directory-index/assets/mimetypes/text-x-c++hdr.png .hpp .hxx
    AddIcon /fancy-directory-index/assets/mimetypes/text-x-c++src.png .cpp .cxx
    # Other programming langs
    AddIcon /fancy-directory-index/assets/mimetypes/text-x-python.png .py
    AddIcon /fancy-directory-index/assets/mimetypes/text-x-perl.png .pl
    AddIcon /fancy-directory-index/assets/mimetypes/text-x-javascript.png .js
    AddIcon /fancy-directory-index/assets/mimetypes/application-x-php.png .php
    AddIcon /fancy-directory-index/assets/mimetypes/application-x-ruby.png .rb .ruby
    AddIcon /fancy-directory-index/assets/mimetypes/text-css.png .css
    AddIcon /fancy-directory-index/assets/mimetypes/text-x-go.png .go
    # Misc.
    AddIcon /fancy-directory-index/assets/mimetypes/text-html.png .html
    AddIcon /fancy-directory-index/assets/mimetypes/text-x-json.png .json
    AddIcon /fancy-directory-index/assets/mimetypes/text-xml.png .xml
    AddIcon /fancy-directory-index/assets/mimetypes/text-calendar.png .ics
    AddIcon /fancy-directory-index/assets/mimetypes/application-x-sharedlib.png .conf
    AddIcon /fancy-directory-index/assets/mimetypes/application-x-sqlite3.png .db .sqlite3
    AddIcon /fancy-directory-index/assets/mimetypes/application-x-mswrite.png .odt .docx
    AddIcon /fancy-directory-index/assets/mimetypes/application-vnd.ms-excel.png .ods .xlsx
    AddIcon /fancy-directory-index/assets/mimetypes/x-office-calendar.png .ics
    AddIcon /fancy-directory-index/assets/mimetypes/folder-up.png ..
    AddIcon /fancy-directory-index/assets/mimetypes/folder.png ^^DIRECTORY^^
    AddIcon /assets/icon.gif ^^BLANKICON^^
    DefaultIcon /fancy-directory-index/assets/mimetypes/unknown.png
</directory>