# This Alias must point to the directory where the git repo is installed
Alias "/fancy-directory-index/" "/data/www/fancy-directory-index/"
#
#   Icon theme: apt install breeze-icon-theme
#
Alias "/fdi-icon-theme/" "/usr/share/icons/breeze/"
#
#   Install
#   cp example.conf /etc/apache2/sites-available/fancy-directory-index.conf
#   a2ensite fancy-directory-index.conf
#
<Directory />
    AllowOverride None
    allow from all
    #Enable Dirlist & ENable Sym Links
    Options Indexes MultiViews FollowSymLinks
    # Dirlist
    IndexOptions +FoldersFirst
    IndexOptions +SuppressHTMLPreamble
    IndexOptions +IconsAreLinks
    IndexOptions +SuppressDescription
    # Load Custon Site
    AddType text/html .shtml
    HeaderName /fancy-directory-index/HEADER.shtml
    ReadmeName /fancy-directory-index/README.shtml
    
    #Custom Icons
    AddIconByType (IMG,/fdi-icon-theme/mimetypes/64/image-x-generic.svg) image/*
    AddIconByType (TXT,/fdi-icon-theme/mimetypes/64/text-x-generic.svg) text/*
    AddIconByType (AUD,/fdi-icon-theme/mimetypes/64/audio-mp3.svg) audio/*
    AddIconByType (PDF,/fdi-icon-theme/mimetypes/64/application-pdf.svg) application/pdf
    AddIconByType (VID,/fdi-icon-theme/mimetypes/64/video-x-generic.svg) video/*
    # archives
    AddIcon /fdi-icon-theme/mimetypes/64/application-x-tar.svg .tar.gz .tar.xz .tar
    AddIcon /fdi-icon-theme/mimetypes/64/application-zip.svg .zip .7z
    # C/C++
    AddIcon /fdi-icon-theme/mimetypes/64/text-x-chdr.svg .h
    AddIcon /fdi-icon-theme/mimetypes/64/text-x-csrc.svg .c
    AddIcon /fdi-icon-theme/mimetypes/64/text-x-c++hdr.svg .hpp .hxx
    AddIcon /fdi-icon-theme/mimetypes/64/text-x-c++src.svg .cpp .cxx
    # Other programming langs
    AddIcon /fdi-icon-theme/mimetypes/64/text-x-python.svg .py
    AddIcon /fdi-icon-theme/mimetypes/64/text-x-perl.svg .pl
    AddIcon /fdi-icon-theme/mimetypes/64/text-x-javascript.svg .js
    AddIcon /fdi-icon-theme/mimetypes/64/application-x-php.svg .php
    AddIcon /fdi-icon-theme/mimetypes/64/application-x-ruby.svg .rb .ruby
    AddIcon /fdi-icon-theme/mimetypes/64/text-x-css.svg .css
    AddIcon /fdi-icon-theme/mimetypes/64/text-x-scss.svg .scss
    AddIcon /fdi-icon-theme/mimetypes/64/text-x-go.svg .go
    # Misc.
    AddIcon /fdi-icon-theme/mimetypes/64/text-html.svg .html
    AddIcon /fdi-icon-theme/mimetypes/64/text-x-json.svg .json
    AddIcon /fdi-icon-theme/mimetypes/64/text-xml.svg .xml
    AddIcon /fdi-icon-theme/mimetypes/64/application-x-sharedlib.svg .conf
    AddIcon /fdi-icon-theme/mimetypes/64/application-x-sqlite3.svg .db .sqlite3
    AddIcon /fdi-icon-theme/mimetypes/64/application-x-mswrite.svg .odt .docx
    AddIcon /fdi-icon-theme/mimetypes/64/application-vnd.ms-excel.svg .ods .xlsx
    AddIcon /fdi-icon-theme/mimetypes/64/x-office-calendar.svg .ics
    AddIcon /fdi-icon-theme/places/64/desktop.svg ..
    AddIcon /fdi-icon-theme/places/96/folder.svg ^^DIRECTORY^^
    AddIcon /assets/icon.gif ^^BLANKICON^^
    DefaultIcon /fdi-icon-theme/mimetypes/64/unknown.svg
</directory>