# This Alias must point to the directory where the git repo is installed
Alias "/fancy-directory-index/" "/data/www/fancy-directory-index/"
Alias "/fdi-icon-theme/" "/usr/share/icons/oxygen/"

<Directory />
    #Enable Dirlist & ENable Sym Links
    Options Indexes MultiViews FollowSymLinks
    # Dirlist
    IndexOptions +FoldersFirst
    IndexOptions +SuppressHTMLPreamble
    IndexOptions +IconsAreLinks
    IndexOptions +SuppressDescription
    # Load Custon Site
    AddType text/html .shtml
    HeaderName /fancy-directory-index/HEADER.shtml
    ReadmeName /fancy-directory-index/README.shtml
    #Custom Icons
    #Custom Icons
    AddIconByType (IMG,/assets/icons/application-images.svg) image/*
    AddIconByType (TXT,/assets/icons/application-text.svg) text/*
    AddIconByType (AUD,/assets/icons/application-audio-playlist.svg) audio/*
    AddIconByType (PDF,/assets/icons/application-pdf.svg) application/pdf
    AddIconByType (VID,/assets/icons/application-video.svg) video/*
    # C/C++
    AddIcon /assets/icons/coding/text-x-chdr.svg .h
    AddIcon /assets/icons/coding/text-x-csrc.svg .c
    AddIcon /assets/icons/coding/text-x-c++hdr.svg .hpp .hxx
    AddIcon /assets/icons/coding/text-x-c++src.svg .cpp .cxx
    # Other programming langs
    AddIcon /assets/icons/coding/text-x-python.svg .py
    # Misc.
    AddIcon /assets/icons/libreoffice-web.svg .html .php  
    AddIcon /assets/icons/office.svg .odt .docx
    AddIcon /assets/icons/application-table.svg .ods .xlsx
    AddIcon /assets/icons/x-office-calendar.svg .ics
    AddIcon /assets/icons/folder-green-desktop.svg ..
    AddIcon /assets/icons/folder-green.svg ^^DIRECTORY^^
    AddIcon /assets/icon.gif ^^BLANKICON^^
    DefaultIcon /assets/icons/unknown.svg
</directory>